# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos9611-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a50s,$(TARGET_DEVICE)),)

endif
